# Generated by Django 5.2.7 on 2025-10-18 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ها',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='شناسه یکتا')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/', verbose_name='تصویر')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('published_time', models.TimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('updated_time', models.TimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نوشته ها',
                'verbose_name_plural': 'نوشته ها',
                'ordering': ['-published_date', '-published_time'],
            },
        ),
    ]
